# Generated by Django 5.0 on 2024-02-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolimlar',
            name='Bolim_fanlari',
            field=models.CharField(default='Bolimlar', max_length=500),
            preserve_default=False,
        ),
    ]
