# Generated by Django 5.0 on 2024-02-03 15:12

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bolimlar_bolim_fanlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifa',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
